### ISSUE TITLE
CUDA out of memory while begin to cluster after epoch 128

### ISSUE THREAD

**Issue by liuxuexun** [weiguangzhao/PBNet#12]
Hi, thank you for opening your great work!

I try your source code and have not any modification. I keep batchsize 4 per gpu and use 3 gpu. All hyperparameters are kept default. 

I try to set the batchsize to 2 per gpu, however, it run several steps and still go out of memory. I would like to know if you also have such a issue and how can I run the code for 4 batchsize.

While the epoch is lower than 128, it works well. I guess it is because of the score net. 

My device is 24G RTX4090, cuda11.3, torch version is 12.0 (I have tried 10.0 and occur a gpu problem).

Thank you!

**Comment by weiguangzhao** [comment]
could you please provide the screenshot of the error? or detailed error log

**Comment by liuxuexun** [comment]
Thank you for your reply!

Here is my error log:
```
Traceback (most recent call last):
  File "train.py", line 416, in <module>
    mp.spawn(Distributed_training, nprocs=cfg.gpu_per_node, args=(cfg,))
  File "/data/liuxuexun/miniconda3/envs/pbnet2/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/data/liuxuexun/miniconda3/envs/pbnet2/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/data/liuxuexun/miniconda3/envs/pbnet2/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/data/liuxuexun/miniconda3/envs/pbnet2/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/data/liuxuexun/code/work2/PBNet/train.py", line 387, in Distributed_training
    train_epoch(dataset.train_data_loader, model, model_fn, optimizer, epoch)
  File "/data/liuxuexun/code/work2/PBNet/train.py", line 54, in train_epoch
    loss, _, visual_dict, meter_dict = model_fn(batch, model, epoch, cfg, task='train')
  File "/data/liuxuexun/code/work2/PBNet/network/PBNet.py", line 357, in model_fn
    ret = model(feat_voxel, xyz_voxel, xyz_original, v2p_index, ins_label, epoch, task)
  File "/data/liuxuexun/miniconda3/envs/pbnet2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/liuxuexun/miniconda3/envs/pbnet2/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/data/liuxuexun/miniconda3/envs/pbnet2/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 969, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/data/liuxuexun/miniconda3/envs/pbnet2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/liuxuexun/code/work2/PBNet/network/PBNet.py", line 272, in forward
    IOU_feat = self.score_Unet(inputs_v3)
  File "/data/liuxuexun/miniconda3/envs/pbnet2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/liuxuexun/code/work2/PBNet/network/Mink.py", line 348, in forward
    out = self.block8(out)
  File "/data/liuxuexun/miniconda3/envs/pbnet2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/liuxuexun/miniconda3/envs/pbnet2/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/data/liuxuexun/miniconda3/envs/pbnet2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/liuxuexun/miniconda3/envs/pbnet2/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg/MinkowskiEngine/modules/resnet_block.py", line 59, in forward
    out = self.conv2(out)
  File "/data/liuxuexun/miniconda3/envs/pbnet2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/liuxuexun/miniconda3/envs/pbnet2/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg/MinkowskiEngine/MinkowskiConvolution.py", line 314, in forward
    outfeat = self.conv.apply(
  File "/data/liuxuexun/miniconda3/envs/pbnet2/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg/MinkowskiEngine/MinkowskiConvolution.py", line 72, in forward
    return fw_fn(
RuntimeError: CUDA out of memory. Tried to allocate 186.00 MiB (GPU 0; 23.64 GiB total capacity; 22.08 GiB already allocated; 68.69 MiB free; 22.48 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by weiguangzhao** [comment]
24G is enough for batchsize 4. 
1. You can check the TensorBoard logs to determine if poor semantic segmentation training has resulted in a large number of floor or wall points being misclassified as instances. 
2. Have you scaled the XYZ coordinates?
3. Try to reduce the max_crops_p from 300000 to 200000   in the config file

**Comment by liuxuexun** [comment]
Hi, thank you for your suggest, I am sorry to bother you at weekend.

1. Here is part of my training los:

```
[2024-11-15 13:19:32,600  INFO  train.py  line 125  2491476]  >>>>>>>>>>>>>>>> Start Evaluation >>>>>>>>>>>>>>>>
[2024-11-15 13:20:20,313  INFO  train.py  line 273  2491476]  epoch: 96/520, total loss: -0.0652, sem loss: 0.4173, offset norm loss: 0.3825, offset dir loss: -0.8650,,  time: 47.71010708808899s
[2024-11-15 13:20:20,315  INFO  train.py  line 294  2491476]  mIoU/mAcc/allAcc 0.7027/0.8001/0.8883.
[2024-11-15 13:21:56,311  INFO  train.py  line 103  2491476]  epoch: 97/520, train loss: -0.1457,  time: 95.98659133911133s
[2024-11-15 13:21:57,096  INFO  train.py  line 119  2491476]  Saving ./log/2024-11-15_10-24-32/000000097.pth
[2024-11-15 13:23:33,552  INFO  train.py  line 103  2491476]  epoch: 98/520, train loss: -0.1480,  time: 96.4353539943695s
[2024-11-15 13:23:34,410  INFO  train.py  line 119  2491476]  Saving ./log/2024-11-15_10-24-32/000000098.pth
[2024-11-15 13:25:10,009  INFO  train.py  line 103  2491476]  epoch: 99/520, train loss: -0.1527,  time: 95.57884478569031s
[2024-11-15 13:25:10,873  INFO  train.py  line 119  2491476]  Saving ./log/2024-11-15_10-24-32/000000099.pth
[2024-11-15 13:26:46,948  INFO  train.py  line 103  2491476]  epoch: 100/520, train loss: -0.1671,  time: 96.05449438095093s
[2024-11-15 13:26:47,814  INFO  train.py  line 119  2491476]  Saving ./log/2024-11-15_10-24-32/000000100.pth
[2024-11-15 13:26:47,834  INFO  train.py  line 125  2491476]  >>>>>>>>>>>>>>>> Start Evaluation >>>>>>>>>>>>>>>>
[2024-11-15 13:27:35,018  INFO  train.py  line 273  2491476]  epoch: 100/520, total loss: -0.0704, sem loss: 0.4180, offset norm loss: 0.3774, offset dir loss: -0.8658,,  time: 47.18136119842529s
[2024-11-15 13:27:35,021  INFO  train.py  line 294  2491476]  mIoU/mAcc/allAcc 0.6988/0.7957/0.8883.
[2024-11-15 13:29:10,527  INFO  train.py  line 103  2491476]  epoch: 101/520, train loss: -0.1626,  time: 95.49798655509949s
[2024-11-15 13:29:11,275  INFO  train.py  line 119  2491476]  Saving ./log/2024-11-15_10-24-32/000000101.pth
[2024-11-15 13:30:46,213  INFO  train.py  line 103  2491476]  epoch: 102/520, train loss: -0.1545,  time: 94.91780710220337s
[2024-11-15 13:30:47,075  INFO  train.py  line 119  2491476]  Saving ./log/2024-11-15_10-24-32/000000102.pth
[2024-11-15 13:32:22,296  INFO  train.py  line 103  2491476]  epoch: 103/520, train loss: -0.1683,  time: 95.2022352218628s
[2024-11-15 13:32:23,200  INFO  train.py  line 119  2491476]  Saving ./log/2024-11-15_10-24-32/000000103.pth
[2024-11-15 13:33:59,564  INFO  train.py  line 103  2491476]  epoch: 104/520, train loss: -0.1716,  time: 96.3419623374939s
[2024-11-15 13:34:00,615  INFO  train.py  line 119  2491476]  Saving ./log/2024-11-15_10-24-32/000000104.pth
[2024-11-15 13:34:00,635  INFO  train.py  line 125  2491476]  >>>>>>>>>>>>>>>> Start Evaluation >>>>>>>>>>>>>>>>
[2024-11-15 13:34:48,952  INFO  train.py  line 273  2491476]  epoch: 104/520, total loss: -0.0888, sem loss: 0.4067, offset norm loss: 0.3728, offset dir loss: -0.8682,,  time: 48.313562870025635s
[2024-11-15 13:34:48,955  INFO  train.py  line 294  2491476]  mIoU/mAcc/allAcc 0.7038/0.7973/0.8923.
[2024-11-15 13:36:24,895  INFO  train.py  line 103  2491476]  epoch: 105/520, train loss: -0.1775,  time: 95.93347120285034s
[2024-11-15 13:36:25,642  INFO  train.py  line 119  2491476]  Saving ./log/2024-11-15_10-24-32/000000105.pth
[2024-11-15 13:38:02,136  INFO  train.py  line 103  2491476]  epoch: 106/520, train loss: -0.1730,  time: 96.46910905838013s
[2024-11-15 13:38:03,012  INFO  train.py  line 119  2491476]  Saving ./log/2024-11-15_10-24-32/000000106.pth
[2024-11-15 13:39:39,153  INFO  train.py  line 103  2491476]  epoch: 107/520, train loss: -0.1605,  time: 96.11879682540894s
[2024-11-15 13:39:40,038  INFO  train.py  line 119  2491476]  Saving ./log/2024-11-15_10-24-32/000000107.pth
[2024-11-15 13:41:14,805  INFO  train.py  line 103  2491476]  epoch: 108/520, train loss: -0.1704,  time: 94.74788117408752s
[2024-11-15 13:41:15,730  INFO  train.py  line 119  2491476]  Saving ./log/2024-11-15_10-24-32/000000108.pth
[2024-11-15 13:41:15,746  INFO  train.py  line 125  2491476]  >>>>>>>>>>>>>>>> Start Evaluation >>>>>>>>>>>>>>>>
[2024-11-15 13:42:03,220  INFO  train.py  line 273  2491476]  epoch: 108/520, total loss: -0.0860, sem loss: 0.4070, offset norm loss: 0.3749, offset dir loss: -0.8679,,  time: 47.469791650772095s
[2024-11-15 13:42:03,223  INFO  train.py  line 294  2491476]  mIoU/mAcc/allAcc 0.7044/0.8070/0.8903.
[2024-11-15 13:43:40,540  INFO  train.py  line 103  2491476]  epoch: 109/520, train loss: -0.1757,  time: 97.30914211273193s
[2024-11-15 13:43:41,306  INFO  train.py  line 119  2491476]  Saving ./log/2024-11-15_10-24-32/000000109.pth
[2024-11-15 13:45:15,956  INFO  train.py  line 103  2491476]  epoch: 110/520, train loss: -0.1893,  time: 94.62984299659729s
[2024-11-15 13:45:16,905  INFO  train.py  line 119  2491476]  Saving ./log/2024-11-15_10-24-32/000000110.pth
[2024-11-15 13:46:51,912  INFO  train.py  line 103  2491476]  epoch: 111/520, train loss: -0.1691,  time: 94.98392295837402s
[2024-11-15 13:46:52,799  INFO  train.py  line 119  2491476]  Saving ./log/2024-11-15_10-24-32/000000111.pth
[2024-11-15 13:48:27,929  INFO  train.py  line 103  2491476]  epoch: 112/520, train loss: -0.1840,  time: 95.11339521408081s
[2024-11-15 13:48:28,815  INFO  train.py  line 119  2491476]  Saving ./log/2024-11-15_10-24-32/000000112.pth
[2024-11-15 13:48:28,830  INFO  train.py  line 125  2491476]  >>>>>>>>>>>>>>>> Start Evaluation >>>>>>>>>>>>>>>>
[2024-11-15 13:49:16,678  INFO  train.py  line 273  2491476]  epoch: 112/520, total loss: -0.0430, sem loss: 0.4454, offset norm loss: 0.3775, offset dir loss: -0.8659,,  time: 47.844698667526245s
[2024-11-15 13:49:16,680  INFO  train.py  line 294  2491476]  mIoU/mAcc/allAcc 0.6889/0.7954/0.8853.
[2024-11-15 13:50:52,703  INFO  train.py  line 103  2491476]  epoch: 113/520, train loss: -0.1890,  time: 96.01497435569763s
[2024-11-15 13:50:53,460  INFO  train.py  line 119  2491476]  Saving ./log/2024-11-15_10-24-32/000000113.pth
[2024-11-15 13:52:29,559  INFO  train.py  line 103  2491476]  epoch: 114/520, train loss: -0.1800,  time: 96.08232951164246s
[2024-11-15 13:52:30,420  INFO  train.py  line 119  2491476]  Saving ./log/2024-11-15_10-24-32/000000114.pth
[2024-11-15 13:54:05,951  INFO  train.py  line 103  2491476]  epoch: 115/520, train loss: -0.2176,  time: 95.50404930114746s
[2024-11-15 13:54:06,803  INFO  train.py  line 119  2491476]  Saving ./log/2024-11-15_10-24-32/000000115.pth
[2024-11-15 13:55:42,889  INFO  train.py  line 103  2491476]  epoch: 116/520, train loss: -0.2016,  time: 96.065260887146s
[2024-11-15 13:55:43,810  INFO  train.py  line 119  2491476]  Saving ./log/2024-11-15_10-24-32/000000116.pth
[2024-11-15 13:55:43,832  INFO  train.py  line 125  2491476]  >>>>>>>>>>>>>>>> Start Evaluation >>>>>>>>>>>>>>>>
[2024-11-15 13:56:31,374  INFO  train.py  line 273  2491476]  epoch: 116/520, total loss: -0.0713, sem loss: 0.4287, offset norm loss: 0.3688, offset dir loss: -0.8687,,  time: 47.53889322280884s
[2024-11-15 13:56:31,376  INFO  train.py  line 294  2491476]  mIoU/mAcc/allAcc 0.7051/0.7906/0.8911.
[2024-11-15 13:58:07,834  INFO  train.py  line 103  2491476]  epoch: 117/520, train loss: -0.1842,  time: 96.45128226280212s
[2024-11-15 13:58:08,589  INFO  train.py  line 119  2491476]  Saving ./log/2024-11-15_10-24-32/000000117.pth
[2024-11-15 13:59:43,824  INFO  train.py  line 103  2491476]  epoch: 118/520, train loss: -0.1902,  time: 95.21906328201294s
[2024-11-15 13:59:44,683  INFO  train.py  line 119  2491476]  Saving ./log/2024-11-15_10-24-32/000000118.pth
[2024-11-15 14:01:20,664  INFO  train.py  line 103  2491476]  epoch: 119/520, train loss: -0.1771,  time: 95.9618091583252s
[2024-11-15 14:01:21,519  INFO  train.py  line 119  2491476]  Saving ./log/2024-11-15_10-24-32/000000119.pth
[2024-11-15 14:02:57,322  INFO  train.py  line 103  2491476]  epoch: 120/520, train loss: -0.1953,  time: 95.78535604476929s
[2024-11-15 14:02:58,183  INFO  train.py  line 119  2491476]  Saving ./log/2024-11-15_10-24-32/000000120.pth
[2024-11-15 14:02:58,200  INFO  train.py  line 125  2491476]  >>>>>>>>>>>>>>>> Start Evaluation >>>>>>>>>>>>>>>>
[2024-11-15 14:03:45,364  INFO  train.py  line 273  2491476]  epoch: 120/520, total loss: -0.0889, sem loss: 0.4150, offset norm loss: 0.3660, offset dir loss: -0.8700,,  time: 47.160337686538696s
[2024-11-15 14:03:45,367  INFO  train.py  line 294  2491476]  mIoU/mAcc/allAcc 0.7076/0.8074/0.8921.
[2024-11-15 14:05:22,013  INFO  train.py  line 103  2491476]  epoch: 121/520, train loss: -0.1889,  time: 96.63909816741943s
[2024-11-15 14:05:22,770  INFO  train.py  line 119  2491476]  Saving ./log/2024-11-15_10-24-32/000000121.pth
[2024-11-15 14:06:59,120  INFO  train.py  line 103  2491476]  epoch: 122/520, train loss: -0.2014,  time: 96.33055067062378s
[2024-11-15 14:07:00,014  INFO  train.py  line 119  2491476]  Saving ./log/2024-11-15_10-24-32/000000122.pth
[2024-11-15 14:08:35,294  INFO  train.py  line 103  2491476]  epoch: 123/520, train loss: -0.2315,  time: 95.26019167900085s
[2024-11-15 14:08:36,142  INFO  train.py  line 119  2491476]  Saving ./log/2024-11-15_10-24-32/000000123.pth
[2024-11-15 14:10:12,246  INFO  train.py  line 103  2491476]  epoch: 124/520, train loss: -0.2241,  time: 96.0864474773407s
[2024-11-15 14:10:13,107  INFO  train.py  line 119  2491476]  Saving ./log/2024-11-15_10-24-32/000000124.pth
[2024-11-15 14:10:13,125  INFO  train.py  line 125  2491476]  >>>>>>>>>>>>>>>> Start Evaluation >>>>>>>>>>>>>>>>
[2024-11-15 14:11:01,096  INFO  train.py  line 273  2491476]  epoch: 124/520, total loss: -0.0811, sem loss: 0.4127, offset norm loss: 0.3738, offset dir loss: -0.8676,,  time: 47.968700647354126s
[2024-11-15 14:11:01,099  INFO  train.py  line 294  2491476]  mIoU/mAcc/allAcc 0.7019/0.7916/0.8917.
[2024-11-15 14:12:37,530  INFO  train.py  line 103  2491476]  epoch: 125/520, train loss: -0.2452,  time: 96.42434668540955s
[2024-11-15 14:12:38,285  INFO  train.py  line 119  2491476]  Saving ./log/2024-11-15_10-24-32/000000125.pth
[2024-11-15 14:14:13,939  INFO  train.py  line 103  2491476]  epoch: 126/520, train loss: -0.2008,  time: 95.63491559028625s
[2024-11-15 14:14:14,801  INFO  train.py  line 119  2491476]  Saving ./log/2024-11-15_10-24-32/000000126.pth
[2024-11-15 14:15:52,062  INFO  train.py  line 103  2491476]  epoch: 127/520, train loss: -0.2320,  time: 97.24012517929077s
[2024-11-15 14:15:52,918  INFO  train.py  line 119  2491476]  Saving ./log/2024-11-15_10-24-32/000000127.pth
[2024-11-15 14:17:28,987  INFO  train.py  line 103  2491476]  epoch: 128/520, train loss: -0.2037,  time: 96.05051183700562s
[2024-11-15 14:17:29,845  INFO  train.py  line 119  2491476]  Saving ./log/2024-11-15_10-24-32/000000128.pth
[2024-11-15 14:17:29,860  INFO  train.py  line 125  2491476]  >>>>>>>>>>>>>>>> Start Evaluation >>>>>>>>>>>>>>>>
[2024-11-15 14:18:17,398  INFO  train.py  line 273  2491476]  epoch: 128/520, total loss: -0.1032, sem loss: 0.3974, offset norm loss: 0.3690, offset dir loss: -0.8695,,  time: 47.53583002090454s
[2024-11-15 14:18:17,402  INFO  train.py  line 294  2491476]  mIoU/mAcc/allAcc 0.7137/0.8194/0.8942.
```
I think the iou is high enough.

2. No any scaled I have done. I have not made any modification of the source code.

3. I  reduce the max_crops_p from 300000 to 200000 and still out of momery when 4 batchsize, I try 100000 points and it can work, However I think it will cause performance degradation ?

I am wondering if the different version of  Minkowskiengine would cause this problem?

**Comment by weiguangzhao** [comment]
1. you can try 150000 points and it will cause performance degradation but not too much
2. Or you can try to train the backbone first about 512 epoch then froze the backbone weight to train the scorenet. In this way，the performance will be par to the original result

**Comment by liuxuexun** [comment]
Ok, thank you, I will have a try.
